import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:4173/#/'); await p.waitForTimeout(1500);
await p.evaluate(() => localStorage.clear()); await p.reload(); await p.waitForTimeout(1800);
console.log('이미지 로드 실패:', await p.evaluate(() => Array.from(document.images).filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src)));
await p.screenshot({ path: '/tmp/p-home.png', fullPage: true });
await p.click('.cta'); await p.waitForTimeout(900);
await p.screenshot({ path: '/tmp/p-certify.png', fullPage: true });
await p.click('.privacy summary'); await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/p-privacy.png', fullPage: true });
await p.setInputFiles('input[type=file]', 'public/sample.png'); await p.waitForTimeout(1600);
await p.getByRole('button', { name: '이대로' }).click(); await p.waitForTimeout(900);
await p.getByRole('button', { name: '카드 뽑기' }).click(); await p.waitForTimeout(2200);
console.log('카드:', await p.evaluate(() => ({ holo: document.querySelectorAll('.holo').length })));
console.log('ERRORS:', errs.length?errs.join(' | '):'none');
await b.close();
