import { chromium } from 'playwright';
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:420,height:900}});
await p.goto('http://localhost:4173/#/tiers'); await p.waitForTimeout(2500);
await p.evaluate(()=>{const g=document.querySelector('.tier-grid');g.style.gridTemplateColumns='1fr';
document.querySelectorAll('.tier-grid .holo').forEach(h=>h.style.maxWidth='340px');
document.querySelectorAll('.holo').forEach(el=>{el.style.setProperty('--mx','64%');el.style.setProperty('--my','38%');el.style.setProperty('--posx','59%');el.style.setProperty('--posy','42%');el.style.setProperty('--hyp','0.6');el.classList.add('active')})});
await p.waitForTimeout(800);
await p.screenshot({path:'/tmp/t.png', fullPage:true});
const tops = await p.evaluate(()=>[...document.querySelectorAll('.tier-grid > div')].map(d=>Math.round(d.getBoundingClientRect().top+scrollY)));
console.log(JSON.stringify(tops));
await b.close();
